name: Deploy Microservices

on:
  push:
    branches:
      - main
    paths:
      - 'microservices-deployment.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to get access to your files
      - name: Checkout repository
        uses: actions/checkout@v2

      # # Set up Kubernetes environment with kubectl
      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     kubectl-version: 'v1.24.0'  # You can set the version based on your Kubernetes version

      # # Configure Kubernetes credentials
      # - name: Configure kubectl with K8S credentials
      #   run: |
      #     echo "$KUBECONFIG" > ~/.kube/config  # Set KUBECONFIG in GitHub Secrets

      # Apply the microservices-deployment.yaml file to the cluster
      - name: Deploy microservices
        run: |
          kubectl apply -f microservices-deployment.yaml

      # # Check the status of the deployment
      # - name: Check deployment status
      #   run: |
      #     kubectl rollout status deployment <your-deployment-name>
