name: Deploy Microservices

on:
  workflow_dispatch:  # Trigger the workflow manually via the GitHub UI

jobs:
  deploy:
    runs-on: lab-marypearl-arc-runners-set  # Self-hosted GitHub runner name

    steps:
      # Checkout the repository to get access to your files
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up kubectl (corrected input to 'version' instead of 'kubectl-version')
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'  # Correct input, specify the desired kubectl version

      # Ensure the .kube directory exists and configure kubectl with Kubernetes credentials (Azure Arc or other K8s clusters)
      - name: Configure kubectl with K8S credentials
        run: |
          mkdir -p ~/.kube  # Ensure the .kube directory exists
          echo "$KUBECONFIG" > ~/.kube/config  # Set KUBECONFIG in GitHub Secrets

      # Apply the microservices-deployment.yaml file to the cluster
      - name: Deploy microservices
        run: |
          pwd
          ls -ltr
          # cd /home/runner/_work/test-gitaction/test-gitaction
          # kubectl apply -f test-gitaction/microservices-deployment.yaml
          kubectl apply -f microservices-deployment.yaml

      # # Check the status of the deployment
      # - name: Check deployment status
      #   run: |
      #     kubectl rollout status deployment <your-deployment-name>
